/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData looks = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cake = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fingerprint = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData flightLand = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData flashAuto = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData freeBreakfast = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData gavel = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData goat = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData http = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData gif = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData hdrOn = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData loyalty = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData motorcycle = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData polymer = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData pool = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData router = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData rowing = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData scanner = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData train = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData timer_10 = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData timer_3 = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData style = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData emoAngry = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData emoCoffee = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData emoDevil = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData emoSurprised = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData cameraAlt = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData faucet = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData headSideMask = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData git_1 = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData feather = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData thList = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData quoteLeft = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData quoteRightAlt = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData hash = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData at = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData semicolon = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData colon = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData artGallery = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData ninetyninedesigns =
      IconData(0xe827, fontFamily: _kFontFam);
  static const IconData meetup = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData ebay_1 = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData lego = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData fivehundredpx = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData android = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData townHall = IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData chrome = IconData(0xe841, fontFamily: _kFontFam);
  static const IconData rocket = IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData batwings = IconData(0xe927, fontFamily: _kFontFam);
  static const IconData boomerang = IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData featheredWing = IconData(0xe9bc, fontFamily: _kFontFam);
  static const IconData lightningTrio = IconData(0xea30, fontFamily: _kFontFam);
  static const IconData tower = IconData(0xead2, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData githubCircled = IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData gplus = IconData(0xf0d5, fontFamily: _kFontFam);
  static const IconData linkedin = IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData github = IconData(0xf113, fontFamily: _kFontFam);
  static const IconData youtube = IconData(0xf167, fontFamily: _kFontFam);
  static const IconData apple = IconData(0xf179, fontFamily: _kFontFam);
  static const IconData digg = IconData(0xf1a6, fontFamily: _kFontFam);
  static const IconData gitSquared = IconData(0xf1d2, fontFamily: _kFontFam);
  static const IconData git = IconData(0xf1d3, fontFamily: _kFontFam);
  static const IconData ccVisa = IconData(0xf1f0, fontFamily: _kFontFam);
  static const IconData motorcycle_1 = IconData(0xf21c, fontFamily: _kFontFam);
  static const IconData streetView = IconData(0xf21d, fontFamily: _kFontFam);
  static const IconData heartbeat = IconData(0xf21e, fontFamily: _kFontFam);
  static const IconData facebookOfficial =
      IconData(0xf230, fontFamily: _kFontFam);
  static const IconData battery_1 = IconData(0xf243, fontFamily: _kFontFam);
  static const IconData registered = IconData(0xf25d, fontFamily: _kFontFam);
  static const IconData bath = IconData(0xf2cd, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xf302, fontFamily: _kFontFam);
  static const IconData twitterBird = IconData(0xf303, fontFamily: _kFontFam);
  static const IconData twitterCircled =
      IconData(0xf30a, fontFamily: _kFontFam);
  static const IconData linkedinSquared =
      IconData(0xf30c, fontFamily: _kFontFam);
  static const IconData gplusCircled = IconData(0xf310, fontFamily: _kFontFam);
  static const IconData logoGist = IconData(0xf342, fontFamily: _kFontFam);
  static const IconData angrycreative = IconData(0xf36e, fontFamily: _kFontFam);
  static const IconData apper = IconData(0xf371, fontFamily: _kFontFam);
  static const IconData cpanel = IconData(0xf388, fontFamily: _kFontFam);
  static const IconData gem = IconData(0xf3a5, fontFamily: _kFontFam);
  static const IconData phoenixFramework =
      IconData(0xf3dc, fontFamily: _kFontFam);
  static const IconData stickerMule = IconData(0xf3f7, fontFamily: _kFontFam);
  static const IconData studiovinari = IconData(0xf3f8, fontFamily: _kFontFam);
  static const IconData amazonPay = IconData(0xf42c, fontFamily: _kFontFam);
  static const IconData php = IconData(0xf457, fontFamily: _kFontFam);
  static const IconData procedures = IconData(0xf487, fontFamily: _kFontFam);
  static const IconData smoking = IconData(0xf48d, fontFamily: _kFontFam);
  static const IconData handHoldingHeart =
      IconData(0xf4be, fontFamily: _kFontFam);
  static const IconData ebay = IconData(0xf4f4, fontFamily: _kFontFam);
  static const IconData balanceScaleRight =
      IconData(0xf516, fontFamily: _kFontFam);
  static const IconData globeAmericas = IconData(0xf57d, fontFamily: _kFontFam);
  static const IconData grinSquintTears =
      IconData(0xf586, fontFamily: _kFontFam);
  static const IconData sadCry = IconData(0xf5b3, fontFamily: _kFontFam);
  static const IconData neos = IconData(0xf612, fontFamily: _kFontFam);
  static const IconData fedex = IconData(0xf797, fontFamily: _kFontFam);
  static const IconData skiing = IconData(0xf7c9, fontFamily: _kFontFam);
  static const IconData skiingNordic = IconData(0xf7ca, fontFamily: _kFontFam);
  static const IconData biking = IconData(0xf84a, fontFamily: _kFontFam);
  static const IconData spellCheck = IconData(0xf891, fontFamily: _kFontFam);
}
