import 'package:ddd_practice_app/_constant/widget_const/custom_icon.dart';
import 'package:flutter/material.dart';

class VelogWidgetCustomIcon extends StatelessWidget {
  const VelogWidgetCustomIcon({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.teal,
        title: const Text('Custom Icon'),
      ),
      body: Padding(
        padding: const EdgeInsets.only(left: 12, right: 12, top: 20),
        child: GridView(
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 7,
            mainAxisSpacing: 10.0,
            crossAxisSpacing: 10.0,
            childAspectRatio: 1.1,
          ),
          children: const [
            Icon(CustomIcon.looks),
            Icon(CustomIcon.cake),
            Icon(CustomIcon.fingerprint),
            Icon(CustomIcon.flightLand),
            Icon(CustomIcon.flashAuto),
            Icon(CustomIcon.freeBreakfast),
            Icon(CustomIcon.gavel),
            Icon(CustomIcon.goat),
            Icon(CustomIcon.http),
            Icon(CustomIcon.gif),
            Icon(CustomIcon.hdrOn),
            Icon(CustomIcon.loyalty),
            Icon(CustomIcon.motorcycle),
            Icon(CustomIcon.polymer),
            Icon(CustomIcon.pool),
            Icon(CustomIcon.router),
            Icon(CustomIcon.rowing),
            Icon(CustomIcon.scanner),
            Icon(CustomIcon.train),
            Icon(CustomIcon.timer_10),
            Icon(CustomIcon.timer_3),
            Icon(CustomIcon.style),
            Icon(CustomIcon.emoAngry),
            Icon(CustomIcon.emoCoffee),
            Icon(CustomIcon.emoDevil),
            Icon(CustomIcon.emoSurprised),
            Icon(CustomIcon.cameraAlt),
            Icon(CustomIcon.faucet),
            Icon(CustomIcon.headSideMask),
            Icon(CustomIcon.git_1),
            Icon(CustomIcon.feather),
            Icon(CustomIcon.thList),
            Icon(CustomIcon.quoteLeft),
            Icon(CustomIcon.quoteRightAlt),
            Icon(CustomIcon.hash),
            Icon(CustomIcon.at),
            Icon(CustomIcon.semicolon),
            Icon(CustomIcon.colon),
            Icon(CustomIcon.artGallery),
            Icon(CustomIcon.ninetyninedesigns),
            Icon(CustomIcon.meetup),
            Icon(CustomIcon.ebay_1),
            Icon(CustomIcon.lego),
            Icon(CustomIcon.fivehundredpx),
            Icon(CustomIcon.android),
            Icon(CustomIcon.townHall),
            Icon(CustomIcon.chrome),
            Icon(CustomIcon.rocket),
            Icon(CustomIcon.batwings),
            Icon(CustomIcon.boomerang),
            Icon(CustomIcon.featheredWing),
            Icon(CustomIcon.lightningTrio),
            Icon(CustomIcon.tower),
            Icon(CustomIcon.facebook),
            Icon(CustomIcon.githubCircled),
            Icon(CustomIcon.gplus),
            Icon(CustomIcon.linkedin),
            Icon(CustomIcon.github),
            Icon(CustomIcon.youtube),
            Icon(CustomIcon.apple),
            Icon(CustomIcon.digg),
            Icon(CustomIcon.gitSquared),
            Icon(CustomIcon.git),
            Icon(CustomIcon.ccVisa),
            Icon(CustomIcon.motorcycle_1),
            Icon(CustomIcon.streetView),
            Icon(CustomIcon.heartbeat),
            Icon(CustomIcon.facebookOfficial),
            Icon(CustomIcon.battery_1),
            Icon(CustomIcon.registered),
            Icon(CustomIcon.bath),
            Icon(CustomIcon.twitter),
            Icon(CustomIcon.twitterBird),
            Icon(CustomIcon.twitterCircled),
            Icon(CustomIcon.linkedinSquared),
            Icon(CustomIcon.gplusCircled),
            Icon(CustomIcon.logoGist),
            Icon(CustomIcon.angrycreative),
            Icon(CustomIcon.apper),
            Icon(CustomIcon.cpanel),
            Icon(CustomIcon.gem),
            Icon(CustomIcon.phoenixFramework),
            Icon(CustomIcon.stickerMule),
            Icon(CustomIcon.studiovinari),
            Icon(CustomIcon.amazonPay),
            Icon(CustomIcon.php),
            Icon(CustomIcon.procedures),
            Icon(CustomIcon.smoking),
            Icon(CustomIcon.handHoldingHeart),
            Icon(CustomIcon.ebay),
            Icon(CustomIcon.balanceScaleRight),
            Icon(CustomIcon.globeAmericas),
            Icon(CustomIcon.grinSquintTears),
            Icon(CustomIcon.sadCry),
            Icon(CustomIcon.neos),
            Icon(CustomIcon.fedex),
            Icon(CustomIcon.skiing),
            Icon(CustomIcon.skiingNordic),
            Icon(CustomIcon.biking),
            Icon(CustomIcon.spellCheck),
          ],
        ),
      ),
    );
  }
}
