class VelogItem {
  List title = [
    'Basic',
    'Container',
    'SizedBox',
    'Animated\nContainer',
    'Custom Icon',
    'List View',
    'Refactor',
    'Text',
    'Animated\nSwitcher',
    'Column',
    'Row',
    'Stateful',
    'Stateless',
    'Stateless_bloc',
    'Hero Animation',
    'Sliver Appbar',
    'BLoC Pattern',
    'Cubit',
    'Provider',
    'Get X',
    'Date Range Picker',
    'Cupertino Time Picker',
    'Custom Bottom Sheet',
    'Custom Slide Screen',
    'Shimmer',
    'Scroll To Index'
  ];
  List router = [
    '/velogWidgetBasic',
    '/velogWidgetContainer',
    '/velogWidgetSizedBox',
    '/velogWidgetAnimatedContainer',
    '/velogWidgetCustomIcon',
    '/velogWidgetListview',
    '/velogWidgetRefactor',
    '/velogWidgetText',
    '/velogWidgetAnimatedSwitcher',
    '/velogWidgetColumn',
    '/velogWidgetRow',
    '/velogWidgetStateful',
    '/velogWidgetStateless',
    '/velogWidgetStatelesswithbloc',
    '/velogWidgetHero',
    '/velogWidgetSliverAppbar',
    '/velogStateBlocPattern',
    '/velogStateCubit',
    '/velogStateProvider',
    '/velogStateGetX',
    '/velogWidgetDateRangePicker',
    '/velogWidgetCupertinoTimePicker',
    '/velogWidgetCustomBottomSheet',
    '/velogWidgetCustomSlideScreen',
    '/velogWidgetShimmer',
    '/velogWidgetScrollToIndex'
  ];
}
